version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "csharp"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "dotnet-format"